### ISSUE TITLE
Resources Reordering Suggestion

### ISSUE THREAD

**Issue by bgeesaman** [joshlarsen/aws-recon#10]
Propose moving:
1. Route53 Zone list-query-logging-configs as a sub resource to the zone
2. VPC describe_flow_logs under describe_vpc

**Comment by joshlarsen** [comment]
Route53 [list_query_logging_configs](https://github.com/darkbitio/aws-recon/commit/799b813a649c859d058fdf2cbf140fd23612294e)

**Comment by joshlarsen** [comment]
VPC [flow logs](https://github.com/darkbitio/aws-recon/commit/8d25f07641a2ef3b33ca7b779d96f98ced967224)
