### ISSUE TITLE
Messy policy document for IAM service

### ISSUE THREAD

**Issue by vvadymv** [joshlarsen/aws-recon#15]
Hello,
produced via ./recon.rb -v --services IAM -r global - JSON policy documents seems messy:
![image](https://user-images.githubusercontent.com/38409513/89883271-97855680-dbd0-11ea-9dbd-eba9999a9c93.png)

commit a861691a8d6c2bc8ae13d108e9c4c0812942349f
> ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

**Comment by joshlarsen** [comment]
We are not parsing policy documents yet. That is the raw format returned by the [AWS API](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/IAM/Client.html#get_account_authorization_details-instance_method).

```ruby
resp.user_detail_list[0].user_policy_list[0].policy_document #=> String
```

We do have it on the roadmap to parse them eventually.
