### ISSUE TITLE
[CloudTrail] AccountID in ARN is wrong error when used with assumed roles 

### ISSUE THREAD

**Issue by thejazzid** [joshlarsen/aws-recon#22]
Hi. 
I have encouraged issues with IAM and CloudTrail when used with Assumed role in to another account, with full readonly permission. (AWS builtIn ReadOnly policy)
Here tracebacks. 
I had to exclude IAM and CloudTrail from collection.

```
Traceback (most recent call last):
	21: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/parallel-1.19.2/lib/parallel.rb:211:in 'block (4 levels) in in_threads'
	20: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/parallel-1.19.2/lib/parallel.rb:360:in 'block in work_in_threads'
	19: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/parallel-1.19.2/lib/parallel.rb:519:in 'with_instrumentation'
	18: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/parallel-1.19.2/lib/parallel.rb:361:in 'block (2 levels) in work_in_threads'
	17: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/parallel-1.19.2/lib/parallel.rb:508:in 'call_with_index'
	16: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws_recon-0.2.7/lib/aws_recon/aws_recon.rb:99:in 'block (2 levels) in start'
	15: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws_recon-0.2.7/lib/aws_recon/aws_recon.rb:49:in 'collect'
	14: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws_recon-0.2.7/lib/aws_recon/collectors/cloudtrail.rb:10:in 'collect'
	13: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws_recon-0.2.7/lib/aws_recon/collectors/cloudtrail.rb:10:in 'each_with_index'
	12: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-3.109.1/lib/aws-sdk-core/pageable_response.rb:93:in 'each'
	11: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws_recon-0.2.7/lib/aws_recon/collectors/cloudtrail.rb:13:in 'block in collect'
	10: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws_recon-0.2.7/lib/aws_recon/collectors/cloudtrail.rb:13:in 'each'
	 9: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws_recon-0.2.7/lib/aws_recon/collectors/cloudtrail.rb:22:in 'block (2 levels) in collect'
	 8: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws-sdk-cloudtrail-1.29.0/lib/aws-sdk-cloudtrail/client.rb:993:in 'list_tags'
	 7: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-3.109.1/lib/seahorse/client/request.rb:72:in 'send_request'
	 6: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-3.109.1/lib/seahorse/client/plugins/response_target.rb:24:in 'call'
	 5: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-3.109.1/lib/aws-sdk-core/plugins/response_paging.rb:12:in 'call'
	 4: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-3.109.1/lib/seahorse/client/plugins/request_callback.rb:71:in 'call'
	 3: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-3.109.1/lib/aws-sdk-core/plugins/param_converter.rb:26:in 'call'
	 2: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-3.109.1/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in 'call'
	 1: from /Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-3.109.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in 'call'
/Users/{USERNAME}/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-3.109.1/lib/seahorse/client/plugins/raise_response_errors.rb:17:in 'call': AccountID in ARN is wrong, you can only access resources with AccountID {AccountNumber}. (Aws::CloudTrail::Errors::CloudTrailARNInvalidException)
```

**Comment by joshlarsen** [comment]
Hi @thejazzid, can you describe your environment a little more? Specifically, can you describe the steps you are taking to authenticate and assume the role? We will try to reproduce it to test.

**Comment by thejazzid** [comment]
Hi @joshlarsen sorry it took some time. 
First of all thanks a lot for a tool. 
Environment is little bit tricky. 
But for aws_recon tool it should be not much complicated. aws_recon called from python script with specific environment variables for credentials. Here a sample of code: 
```
    temp_env = os.environ.copy()
    temp_env['AWS_ACCESS_KEY_ID'] = credentials.access_key
    temp_env['AWS_SECRET_ACCESS_KEY'] = credentials.secret_key
    temp_env['AWS_SESSION_TOKEN'] = credentials.token
    temp_env['AWS_DEFAULT_REGION'] = master_reg
    subprocess.run(['/Users/{USERNAME}/.rvm/gems/ruby-2.6.5/bin/aws_recon', '-v', '-o', file_name, '-x',
                                 'IAM,CloudTrail,Support,CodePipeline,KMS'], env=temp_env)
```
Those credentials are result of assume role operation for specific role inside of specific account, with AWS managed readonly policy attached to that role. 
As you can see I had to exclude some of the services, as they are failing. In general tool runs fine across most of resources and able to collect, but not all. It could be question of permissions, but errors I'm getting not specific on type of access. could be due to AWS SDK itself. But mostly strange thing about wrong account ID ARN, which I have not figured yet out. 
I will continue researching with permissions and will report if any findings.

**Comment by joshlarsen** [comment]
I am separating these into two different issues. The `IAM` issue is now in #66.

**Comment by joshlarsen** [comment]
@thejazzid is the trail an organizational trail? Multi-region?

**Comment by thejazzid** [comment]
Hi @joshlarsen  yes, cloudtrail is global Organization level cloudtrail.

**Comment by PercussiveElbow** [comment]
I've ran into this exact issue - for reference this seems to be an inherent thing with the AWS SDK/CLI. 

An account in an organisation (with the relevant CloudTrail read permissions) can call describe_trails without issue which will return whatever trail that that account logs to, but it will return errors complaining that the trail is in another account when calling specific methods like list_tags, get_event_selectors, get_trail_status etc.

There might be a workaround for this if the permissions for those are manually assigned on the org account with the trail in it, but I've worked around this in a hacky way by modifying https://github.com/joshlarsen/aws-recon/blob/main/lib/aws_recon/collectors/cloudtrail.rb to skip these additional methods if the account ID in the trail arn mismatches the current calling account ID
