### ISSUE TITLE
`user_policy_list.policy_document` is URL encoded

### ISSUE THREAD

**Issue by sdemjanenko** [joshlarsen/aws-recon#23]
When downloading IAM data, the policy_document for each record nested under `user_policy_list` appears to be URL encoded. I was able to use `URI.decode_www_form` on the string to turn it into the actual policy document.

**Comment by joshlarsen** [comment]
Hi @sdemjanenko, thanks for opening this issue. This is definitely something we plan on adding soon.

**Comment by joshlarsen** [comment]
@sdemjanenko we are parsing a number of IAM policy documents now. Let me know how it works for you.
