### ISSUE TITLE
Service inclusion/exclusion should be case insensitive

### ISSUE THREAD

**Issue by ilkka** [joshlarsen/aws-recon#78]
When using e.g. the `-x` flag, it seems like some service names (e.g. AccessAnalyzer) should be given capitalized like in the services list, but others (e.g. DMS) should be given in all lowercase. It's a bit surprising, maybe the matching could be completely case insensitive?

**Comment by joshlarsen** [comment]
The services are referred to by the name AWS uses for the API (e.g. AccessAnalyzer, or DatabaseMigrationService). There are lowercase aliases [defined that are purely for convenience](https://github.com/darkbitio/aws-recon/blob/a7e19ea153584a590ff2dbe05f9a6e087cf53fce/lib/aws_recon/services.yaml#L169) and are not necessarily consistent. We'll look at making them case insensitive in the future.

**Comment by ilkka** [comment]
Ah, that clears it right up for me, thanks!
