### ISSUE TITLE
Only finds ECS clusters named "default"

### ISSUE THREAD

**Issue by ilkka** [joshlarsen/aws-recon#79]
This one is weird, but I can see multiple clusters in multiple accounts in the console. One of the accounts has an ECS cluster named "default". When I run recon with `-s ECS` with the same assumed roles as I used in the console, it _only_ lists the "default" cluster from the account that contains it, and no clusters from any accounts that don't.

**Comment by joshlarsen** [comment]
Good find, thanks. This will be fixed in the next version, later today.
